model-name: "paddlepaddle"
model-category: "pulc_person_attribute"

attributes:
  - name: Hat
    type: multi
    indices: [0]
    options: [Hat]
  - name: Glasses
    type: multi
    indices: [1]
    options: [Glasses]
  - name: Upper
    type: multi
    indices: [2, 3, 4, 5, 6, 7]
    options: [ShortSleeve, LongSleeve, UpperStride, UpperLogo, UpperPlaid, UpperSplice]
  - name: Lower
    type: multi
    indices: [8, 9, 10, 11, 12, 13]
    options: [LowerStripe, LowerPattern, LongCoat, Trousers, Shorts, 'Skirt&Dress']
  - name: Boots
    type: multi
    indices: [14]
    options: [Boots]
  - name: Bag
    type: multi
    indices: [15, 16, 17]
    options: [HandBag, ShoulderBag, Backpack]
  - name: HoldObjectsInFront
    type: multi
    indices: [18]
    options: [HoldObjectsInFront]
  - name: Age
    type: single
    indices: [19, 20, 21]
    options: [AgeLess18, Age18-60, AgeOver60]
  - name: Gender
    type: multi
    indices: [22]
    options: [Female (uncheck = Male)]
  - name: Direction
    type: single
    indices: [23, 24, 25]
    options: [Front, Side, Back]

text-format: "filename.jpg	0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1"
